databases:
  - name: glb-connect-db
    databaseName: glb_connect
    user: glb_user

services:
  - type: web
    name: glb-connect-backend
    env: node
    repo: https://github.com/mb-aarfi/GLB.Connect.git # ❗IMPORTANT: Replace with your actual repo URL
    plan: free
    branch: main
    healthCheckPath: /api/health # You may need to create this simple endpoint
    buildCommand: "npm install && npx prisma migrate deploy && npx prisma generate"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: glb-connect-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          type: web
          name: glb-connect-frontend
          property: url
      - key: NODE_ENV
        value: production

  - type: web
    name: glb-connect-frontend
    plan: free
    env: static
    repo: https://github.com/mb-aarfi/GLB.Connect.git # ❗IMPORTANT: Replace with your actual repo URL
    branch: main
    staticPublishPath: ./client/dist
    buildCommand: "cd client && npm install && npm run build"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: glb-connect-backend
          property: url 